# More documentation about how to customize your build
# can be found here:
# https://docs.fastlane.tools
fastlane_version "1.109.0"

# This value helps us track success metrics for Fastfiles
# we automatically generate. Feel free to remove this line
# once you get things running smoothly!
generated_fastfile_id "690159e2-24ee-49a6-95d6-bc036e2cd42a"

default_platform :ios

# Fastfile actions accept additional configuration, but
# don't worry, fastlane will prompt you for required
# info which you can add here later
lane :beta do
  increment_build_number(
    xcodeproj: ‘./Miraa.xcodeproj'
  )
  gym(
    project: './Miraa.xcodeproj',
    scheme: ‘Miraa’
  )
  pilot
end
